name: authbox-ts

services:
  postgres:
    image: postgres:17-alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DATABASE:-authbox_db}
      POSTGRES_USER: ${POSTGRES_USER:-authbox_admin}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-authbox_password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-authbox_admin} -d ${POSTGRES_DATABASE:-authbox_db}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "${REDIS_PORT:-6379}:6379"
    command: >
      redis-server
      --appendonly yes
      --requirepass ${REDIS_PASSWORD:-authbox_password}
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD:-authbox_password}", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  minio:
    image: minio/minio:RELEASE.2025-09-07T16-13-09Z
    container_name: minio
    restart: unless-stopped
    ports:
      - "9000:9000"   # API
      - "9001:9001"   # Console (disable in prod)
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-authbox_admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-authbox_password}
      MINIO_BROWSER: "on" # set "off" in production
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres-data:
  minio-data:
  redis-data: